# Generated by Django 6.0.1 on 2026-01-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_type',
            field=models.CharField(choices=[('communique', 'Communiqué officiel'), ('note', 'Note d’information'), ('compte_rendu', 'Compte rendu'), ('annonce', 'Annonce'), ('message', 'Message institutionnel')], default='note', max_length=20, verbose_name='Type de contenu'),
        ),
    ]
